I joined all module tasks into this PR.
htmlacademy-ecmascript/997093-cinemaddict-15 pull request #1
Opened 2021-07-28 17:19 UTC by kildim

2021-07-28 17:20 UTC, kildim commented
I joined all module tasks into this PR.

2021-07-28 17:54 UTC, dtsaryov requested changes

2021-07-28 17:54 UTC, dtsaryov commented on public/index.html
> +    <section class="films">
Всё, чего нет изначально в разметке должно отрисовываться с помощью JS.

Откати все изменения в этом файле, пожалуйста, кроме подключения бандла

2021-07-28 17:54 UTC, dtsaryov commented on package.json
> +    "webpack-dev-server": "^3.11.0"
Б19. Версии используемых зависимостей зафиксированы в package.json.

2021-07-28 17:54 UTC, dtsaryov commented on .eslintignore
> -webpack.config.js
Верни, пожалуйста

2021-07-28 17:54 UTC, dtsaryov commented on .eslintrc.yml
> +ignorePatterns: ["temp.js", "**/vendor/*.js"]
А это зачем?

2021-07-28 17:54 UTC, dtsaryov commented on src/main.js
> +const siteHeaderElement = document.querySelector('.header');
Б14. Код всех JS-файлов соответствует рекомендованной структуре.

2021-07-29 20:26 UTC, dtsaryov commented on src/view/films.js
> +            ${generateFilmsList()}
К сожалению, так не получится оставить - сейчас надо все отрендерить в main.js

2021-07-29 20:26 UTC, dtsaryov commented on src/view/films.js
> +  `<section class="films">
Шаблон раз

2021-07-29 20:26 UTC, dtsaryov commented on src/view/films.js
> +      <section class="films-list">
Шаблон два

2021-07-29 20:26 UTC, dtsaryov commented on src/view/films.js
> +      </section>
Шаблон три, который переиспользуется обоих extra секций

2021-07-29 20:26 UTC, dtsaryov commented on src/view/footer-statistics.js
> +  '  </section>'
А откуда вдруг тут конкатенация?

2021-07-29 20:26 UTC, dtsaryov commented on src/main.js
> +};
```JS
const RenderPlace = {
  BEFORE_END: 'beforeend',
  // ..
};

const render = (container, template, place = RenderPlace.BEFORE_END) => ...;
```

2021-07-29 20:26 UTC, dtsaryov commented on src/factories/films-data.js
> +const filmData = {
filmMock

2021-07-29 20:26 UTC, dtsaryov commented on src/factories/films-data.js
> +};
В этом смысла нет

2021-07-29 20:26 UTC, dtsaryov commented on src/factories/films-data.js
> +export {getFilm};
factories -> mocks

2021-07-29 20:26 UTC, dtsaryov commented on src/helpers/film-lists.js
> +};
Пока что можно просто пять раз render вызвать в цикле.

Либо так: 

```JS
new Array(limit).fill(``).map(() => createFilmCardTemplate(filmMock)).join('\n').trim()
```

2021-07-29 20:26 UTC, dtsaryov commented on src/factories/films-data.js
> +};
И давай на будущее договоримся не "мешать" домашки

2021-07-29 20:26 UTC, dtsaryov commented on .eslintrc.yml
> +
Пустые строчки остались

2021-07-29 20:26 UTC, dtsaryov commented on .gitignore
> +public/bundle.js.map
Тут, кстати, можно регулярные выражения использовать: `public/bundle*`

2021-07-29 20:26 UTC, merged